version: '3.8'
services:
  mysql-8.1.0:
    image: vsanyc/docker-mysql-8.1.0-v1
    build:
      context: .
      dockerfile: ./docker-mysql/Dockerfile
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=test_db
    networks:
      - simple-spring-boot-rest-mysql
  spring-boot-rest:
    image: vsanyc/spring-boot-rest-v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://mysql-8.1.0:3306/test_db
    depends_on:
      - mysql-8.1.0
    networks:
      - simple-spring-boot-rest-mysql
networks:
  simple-spring-boot-rest-mysql:
